### ISSUE TITLE
Notify popup in the code

### ISSUE THREAD

**Issue by QuentiumYT** [PRATAP-KUMAR/add-custom-text-to-workspace-indicators#2]
There is a remaining debug code probably in the extension, can it be removed?
`Main.notify('', JSON.stringify(this));` on line 49 from commit https://github.com/PRATAP-KUMAR/add-custom-text-to-workspace-indicators/commit/9c598062aa5ae5008547f241d6a3c8bd63ba1dbb
Thanks

**Comment by pratap-panabaka** [comment]
Hi, thanks for reporting this. I have removed that line.

**Comment by PRATAP-KUMAR** [comment]
@QuentiumYT can I have your email id? Mine is pratap@fastmail.fm, if its ok for you give me your mail id or email me.
