### ISSUE TITLE
Placeholder Icon Appears Even When Disabled

### ISSUE THREAD

**Issue by andreaxhearts** [PRATAP-KUMAR/add-custom-text-to-workspace-indicators#3]
Sometimes the placeholder for brand-logo-symbolic.svg shows up - even though I have 'Show Logo' set to off in the extension preferences. The only setting I have of any consequence is the pill color has been changed, with the other extension features turned off too. I have to toggle the extension on and off to hide it again. A workaround is to create the logo file (with the setting still off) with a single transparent pixel. There won't be an icon in case the bug happens, but instead you'll get a gap next to the workspace indicator.

OS: Ubuntu 23.10
GNOME Version: 45.2
Extension Version: 12

![Screenshot from 2024-01-08 00-53-56](https://github.com/PRATAP-KUMAR/add-custom-text-to-workspace-indicators/assets/109897323/ed93ee59-7c90-4b1c-8e22-2f1632b16247)
![Screenshot from 2024-01-06 18-59-32](https://github.com/PRATAP-KUMAR/add-custom-text-to-workspace-indicators/assets/109897323/fb45f4b3-97d3-4b52-8326-5eb3c6e07c73)

**Comment by pratap-panabaka** [comment]
Hi, thanks for the issue. I have noticed this myself few days ago. I will update the extension soon.
Meanwhile is it ok for you to remove this extension and install it via a script from github.

Use option 2 under Install guide. https://github.com/PRATAP-KUMAR/add-custom-text-to-workspace-indicators

**Comment by pratap-panabaka** [comment]
@andreaxhearts I have updated the extension for gnome-shell v45 and v46.
