### ISSUE TITLE
Q: how to get to the menu?  also, does it work with Wayland disabled?

### ISSUE THREAD

**Issue by jlearman** [PRATAP-KUMAR/add-custom-text-to-workspace-indicators#4]
Two questions:

Does it work with Wayland disabled?  (I position apps using the `--geometry` option, which it doesn't allow.)

How do I get to the menu shown in the README?

**Comment by pratap-panabaka** [comment]
Hi
Do you have gnome extensions tool installed? If not u can acceess via command line

**Comment by jlearman** [comment]
I just installed it (https://github.com/mjakeman/extension-manager) but I don't see how to access that either.  I used the web install button on that site and it seemed to work, and I logged off and back on.

**Comment by jlearman** [comment]
Command line would be great in any case

**Comment by pratap-panabaka** [comment]
Hi, can you provide the output of `gnome-extensions list | grep add-custom` and `gnome-extensions list | grep Add-Custom`

**Comment by jlearman** [comment]
```
Mar/08-12:47:08:~$ gnome-extensions list | grep -i add-custom
add-custom-text-to-workspace-indicators@pratap.fastmail.fm
```

**Comment by pratap-panabaka** [comment]
`gnome-extensions prefs add-custom-text-to-workspace-indicators@pratap.fastmail.fm` this command should open the preferences window of the extension

**Comment by pratap-panabaka** [comment]
Hi @jlearman thanks for 3 coffees. Did it really help? I mean our chat?

**Comment by jlearman** [comment]
The panel comes up, but says "We're very sorry, but there's been a problem: the settings for this extension can't be displayed.  We recommend that you report the issue to the extension authors."
Technical details:
```
ImportError: No JS module 'init' found in search path

Stack trace:
  _init@resource:///org/gnome/Shell/Extensions/js/extensionPrefsDialog.js:24:13
  ExtensionPrefsDialog@resource:///org/gnome/Shell/Extensions/js/extensionPrefsDialog.js:10:4
  OpenExtensionPrefsAsync/<@resource:///org/gnome/Shell/Extensions/js/extensionsService.js:129:33
  asyncCallback@resource:///org/gnome/gjs/modules/core/overrides/Gio.js:115:22
  run@resource:///org/gnome/Shell/Extensions/js/dbusService.js:186:20
  main@resource:///org/gnome/Shell/Extensions/js/main.js:22:13
  run@resource:///org/gnome/gjs/modules/script/package.js:206:19
  start@resource:///org/gnome/gjs/modules/script/package.js:190:8
  @/usr/share/gnome-shell/org.gnome.Shell.Extensions:1:17
  ```

Should I try re-enabling Wayland, just to check?  Or is Wayland beside the point?

It hasn't helped yet, not fully, but I appreciate the quick response and your time is worth it to me.

**Comment by pratap-panabaka** [comment]
Wayland or XOrg does not matter, It should work. what is your gnome version? output of `gnome-shell --version` please.

**Comment by jlearman** [comment]
Mar/08-12:50:41:~$ gnome-shell --version
GNOME Shell 42.9

**Comment by pratap-panabaka** [comment]
Oh, this extension is for gnome-shell version 45 only. for 42 you may try downloading the other extension manually.

https://extensions.gnome.org/extension/4405/replace-activities-text/

![image](https://github.com/PRATAP-KUMAR/add-custom-text-to-workspace-indicators/assets/40719899/f555b228-d21c-444e-a0f4-329c487e8dec)

shell version 42, extension version 14

But this extension is not same as add-custom-text extension

**Comment by jlearman** [comment]
OK thanks!  I think that will meet my needs, though not as nice.  And I need to stick with 22.04.

Again, thanks much for your help.

**Comment by pratap-panabaka** [comment]
@jlearman you can write me clear points on how you would want this extension for gnome-shell v42. I will try to modify the code when I have free time.

Thanks

**Comment by jlearman** [comment]
Actually, all I want is to put the VM name in the window manager title bar, so replace-activities-text should be just fine.

Thanks!
